CREATE TABLE tblusers (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    CreatedOn DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ModifiedOn DATETIME ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Name VARCHAR(100) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Token VARCHAR(255),
    INDEX (Email)
);

CREATE TABLE tblcourses (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    CreatedOn DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ModifiedOn DATETIME ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    Name VARCHAR(100) NOT NULL,
    Duration VARCHAR(50),
    Description TEXT
);

CREATE TABLE tblstudents (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    CreatedOn DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ModifiedOn DATETIME ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    MobileNo VARCHAR(15),
    CourseId INT,
    FOREIGN KEY (CourseId) REFERENCES TblCourses(Id) ON DELETE SET NULL,
    INDEX (Email)
);

GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;
